### ISSUE TITLE
Can't login (Ticket System)

### ISSUE THREAD

**Issue by DanielMarkink** [ChimpGamer/NetworkManager#1]
### What steps do you need to take to reproduce the problem?  
1. Do ingame "/ticket register <password>"
2. Try to login into the ticket page and you will get an wrong password all the time.
3. 
etc.

### What were you expecting to happen? What happens instead?  
It shout log me into the ticket system.

### What version of the plugin are you using? (Type /networkmanager (In-Game))  
![2](https://user-images.githubusercontent.com/30463195/35749095-b5547bb0-0850-11e8-9a20-f2b58283d904.PNG)

### What BungeeCord/Spigot version are you using? (Type /bungee for BungeeCord and /version for Spigot)  
![3](https://user-images.githubusercontent.com/30463195/35749170-01af57b4-0851-11e8-83d6-e1eb781d02eb.PNG)

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com) or [pastebin.com](http://pastebin.com).
I have no errors

### Any additional information that might be useable/important?
By some players it works and other players it don't work.

**Comment by ChimpGamer** [comment]
I've reproduce the problem with your steps but It works fine for me. The username and password are both case sensitive so make sure you have entered the username and password correct.
