### ISSUE TITLE
Command Blocker Custom Response is reset when editing other fields

### ISSUE THREAD

**Issue by MCAlagaesia** [ChimpGamer/NetworkManager#100]
**Describe the bug**
The command blocker custom response is reset to "Custom Message" when any other field is edited on the web interface.

**Steps To Reproduce**
Shown here:
https://www.youtube.com/watch?v=tQPn2MeAGOo

1. Create a new blocked command with a custom response
2. Reload NetworkManager and try using the blocked command. Observe that you receive the custom response.
3. Edit any field except "Custom Response" (e.g. try editing "Command", "Server" or toggling "PermissionBypass")
4. Reload NetworkManager and try using the blocked command. Observe that you receive "The command /command is blocked" and not the custom response that you expected.

**Expected behaviour**
The custom response stays the same when editing other fields

**Screenshots**
https://www.youtube.com/watch?v=tQPn2MeAGOo

**Version Information:**
 - NetworkManager:
```
Developers » ChimpGamer
Version » v2.12.1
Buyer of this plugin » https://www.SpigotMC.org/members/41511
UniqueDownloadId » -135946689
Wiki » https://networkmanager.gitbook.io/wiki/
Support » https://discordapp.com/invite/HvaY4QY
Platform » BungeeCord git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5b246ea:499
Extensions: None
Hooks: 
 PremiumVanish - 2.7.17
```
 - Spigot/Paper:
```
Checking version, please wait...
This server is running Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)\nYou are running the latest version\nPrevious version: git-Paper-283 (MC: 1.18.2)
```
 - Bungee/Waterfall/Proxy:
```
This server is running Waterfall version git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5b246ea:499 by md_5
```

**Comment by ChimpGamer** [comment]
Will be fixed in version 2.8.18 of the web interface.
