### ISSUE TITLE
Add PlaceholderAPI and Vault as softdepend

### ISSUE THREAD

**Issue by WilliDieEnte** [ChimpGamer/NetworkManager#102]
**Is your feature request related to a problem? Please describe.**
Currently NM-Spigot is creating some warnings on every server reboot, because it is accessing other plugins, without having them defined as softdepend. This could easily be fixed by adding them as such. It isn't really important, but would be neat to get less warnings :)

**Describe the solution you'd like**
I would really appreciate it if you'd add PlaceholderAPI, Vault or any other potential plugins NM-Spigot may interact with as softdepend in the plugin.yml. 

**Describe alternatives you've considered**
I've added them myself previously on every update, but it would be beneficial for everyone if it would be changed in NM-Spigot directly

**Additional context**
/

**Comment by ChimpGamer** [comment]
I've added PlaceholderAPI as a softdepend for the next update. I won't add Vault because it's no use. Vault cannot be a soft depend because NetworkManager has to be loaded before vault.

**Comment by WilliDieEnte** [comment]
Thanks!
