### ISSUE TITLE
Discord bot command option "playerlist" and its description not translatable

### ISSUE THREAD

**Issue by KasparMelme** [ChimpGamer/NetworkManager#104]
**Describe the bug**
In Discord Bot extension the option and its description in playerlist is not translatable. 

**Steps To Reproduce**
Steps to reproduce the behaviour:
1. Call /playerlist and the command suggestion appears. There is an option as well as a description but no possibility in command-settings to change.

**Expected behaviour**
A possibility to translate these two things in command settings.

**Screenshots**
https://cdn.discordapp.com/attachments/227773525006614540/1068513192277463121/image.png

**Version Information:**
 - NetworkManager: 2.12.10
 - Discord Bot: 1.7.0
 - Spigot/Paper: 1.19.0
 - Bungee/Waterfall/Proxy: 1.19 R 0.1

**Comment by ChimpGamer** [comment]
Added this in the 1.7.0 build 12
