### ISSUE TITLE
Party list command

### ISSUE THREAD

**Issue by ChimpGamer** [ChimpGamer/NetworkManager#108]
**Is your feature request related to a problem? Please describe.**
At the moment it is not possible to see which public parties are 

**Describe the solution you'd like**
A command which will list all public parties which you will be able to join.
- Pages. Click through the list of public parties.
- Click on party to join.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Michel13xx** [comment]
HiIch möchte nicht mehr benachrichtigt werden über Updates Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: ChimpGamer ***@***.***> Datum: 24.03.23  17:45  (GMT+01:00) An: ChimpGamer/NetworkManager ***@***.***> Cc: Subscribed ***@***.***> Betreff: [ChimpGamer/NetworkManager] Party list command (Issue #108) 
Is your feature request related to a problem? Please describe.
At the moment it is not possible to see which public parties are
Describe the solution you'd like
A command which will list all public parties which you will be able to join.

Pages. Click through the list of public parties.
Click on party to join.

Describe alternatives you've considered
None
Additional context
None

**Comment by ChimpGamer** [comment]
Added in 2.13.3
