### ISSUE TITLE
Auto update in Web panel-

### ISSUE THREAD

**Issue by Rivonivo** [ChimpGamer/NetworkManager#110]
I would find it practical to have autoupdate in the web panel in order to always have the latest version!

**Comment by ChimpGamer** [comment]
That would be nice indeed. I just haven't found a way to do this yet. If anyone knows how to please let me know. For now just follow the update instructions [here](https://github.com/ChimpGamer/NetworkManagerWebbie?tab=readme-ov-file#updating).
