### ISSUE TITLE
Can't add servers in the panel.

### ISSUE THREAD

**Issue by DanielMarkink** [ChimpGamer/NetworkManager#12]
### What steps do you need to take to reproduce the problem?  
1. Go to the "Servers" tab in the web panel.
2. Click "Add server"
3. Enter all the server data.
4. Click "Create"
5. Now the server will not get added to the "Servers" tab nor the database/table.

### What were you expecting to happen? What happens instead?  
Add the server to the database/table and show it in the "Servers" tab.

### What version of the plugin are you using? (Type /networkmanager (In-Game))  
NetworkManager version 2.1.9.1

### What BungeeCord/Spigot version are you using? (Type /bungee for BungeeCord and /version for Spigot)  
BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:fde2c3f:1310

### Any additional information that might be useable/important?
I used the lastest version of the web panel.

**Comment by DanielMarkink** [comment]
Yes, the problem is that the server don’t get added via the web interface into the mysql server.

**Comment by ChimpGamer** [comment]
Did you already tried clearing cache and cookies?

**Comment by ChimpGamer** [comment]
Probably not caused by the code of the Web Interface
