### ISSUE TITLE
When i not join via the bungeecord IP i get all lobbys are full instead of the "Please join via: my.domain.extention".

### ISSUE THREAD

**Issue by DanielMarkink** [ChimpGamer/NetworkManager#14]
### What steps do you need to take to reproduce the problem?  
1. Enable "module_proxy_only" in the panel.
2. Reload the Bungeecord and spigot servers.
3. Try to join via an not added IP.
4. You will get "All our lobby servers are offine!" instead of "NetworkManager
Please join using our BungeeCords!
Use the ip: play.yourserverip.net".

### What were you expecting to happen? What happens instead?  
say "NetworkManager
Please join using our BungeeCords!
Use the ip: play.yourserverip.net" instead of "All our lobby servers are offine!"

### What version of the plugin are you using? (Type /networkmanager (In-Game))  
All our lobby servers are offine!

### What BungeeCord/Spigot version are you using? (Type /bungee for BungeeCord and /version for Spigot)  
BungeeCord: BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:fde2c3f:1310
Spigot: CraftBukkit version git-Spigot-2086bb0-ca057a3 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT

### Any additional information that might be useable/important?
NetworkManagerBridge 1.8.9

**Comment by ChimpGamer** [comment]
Known bug. Will be fixed in the next update that will be released soon!
