### ISSUE TITLE
/nmb about display bugg

### ISSUE THREAD

**Issue by ghost** [ChimpGamer/NetworkManager#15]
### What steps do you need to take to reproduce the problem?  
1. Type "/nmb about" in your spigot
2. You will get https://www.SpigotMC.org/members/%%__USER__%% and the Unique ID for this file is %%__NONCE__%%

### What were you expecting to happen? What happens instead?  
Give my the real link to the member spigot page and the real Unique ID for this file.

### What version of the plugin are you using? (Type /networkmanager (In-Game))  
NetworkManager version 2.1.9.1

### What BungeeCord/Spigot version are you using? (Type /bungee for BungeeCord and /version for Spigot)  
BungeeCord: BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:fde2c3f:1310
Spigot: CraftBukkit version git-Spigot-2086bb0-ca057a3 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT

**Comment by ChimpGamer** [comment]
This is probably caused by the Obfuscation but I'm trying to find a solution for this.

**Comment by ChimpGamer** [comment]
If anyone knows how to fix this issue (I assume it is caused by ProGuard) then hit me up on Discord!
