### ISSUE TITLE
Can't add servers in the panel. (Reopened)

### ISSUE THREAD

**Issue by DanielMarkink** [ChimpGamer/NetworkManager#16]
### What steps do you need to take to reproduce the problem?  
1. Go to the "Servers" tab in the web panel.
2. Click "Add server"
3. Enter the server data (LEAVE AT LEAST THE MOTD EMPTY.)
4. Click "Create"
5. Now the server will not get added to the "Servers" tab nor the database/table.
Add the server to the database/table and show it in the "Servers" tab.
### What were you expecting to happen? What happens instead?  
Add the server to the database/table and show it in the "Servers" tab.

### Did you tried to reproduce the problem on a clean environment?  
Yes.

### What version of the plugin are you using? (Type /networkmanager (In-Game))  
NetworkManager version 2.1.9.1

### What BungeeCord/Spigot version are you using? (Type /bungee for BungeeCord and /version for Spigot)  
BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:fde2c3f:1310

### Any additional information that might be useable/important?
its because no field can be emty
**servername=test&ip=localhost&port=25568&motd=gfgrdg&allowed_versions=1.8&restricted=on&islobby=on**
that works ^^
**servername=test&ip=localhost&port=25568&motd=&allowed_versions=&restricted=on**
that doesn't work ^^
and that one is if i leave an field blank.

**Comment by DanielMarkink** [comment]
The code that the creator has given me will not fix the issue:
**$motd = $_GET['motd'] == '' ? '' : $_GET['motd'];
$allowedversions = $_GET['allowed_versions'] == '' ? '' : $_GET['allowed_versions'];**

Browser console return:
**servername=test&ip=multicraft.dsgnetwork.eu&port=10001&motd=&allowed_versions=&islobby=on**
(Status: Not fixed)

**Comment by ChimpGamer** [comment]
I'm 100% sure it works and it does for others too.

https://gyazo.com/5979da1fd0c2cd1aeb04a2f2ae958644

Like I say in DM on Discord it might be your Web host causing some issues with PHP.

**Comment by DanielMarkink** [comment]
Its not my web host because if i host it on my vps then i have the same issue

**Comment by ChimpGamer** [comment]
Did you tried using another browser and/or another computer? Were the results the same?

**Comment by DanielMarkink** [comment]
It looks like that the problem is because you add every varaible with an new prepaire statement but this wiki says that it all need to be in one statement.
https://www.w3schools.com/php/php_mysql_prepared_statements.asp

**Comment by DanielMarkink** [comment]
And then that will confirm why i can edit and delete servers but not add them.

**Comment by DanielMarkink** [comment]
But please note that this an problem on all pages.

**Comment by ChimpGamer** [comment]
The insert is in one preparedstatement do what are You talking about?

**Comment by DanielMarkink** [comment]
I now run the panel 2.2.0 but still have this issue

**Comment by ChimpGamer** [comment]
Solved!

**Comment by DanielMarkink** [comment]
fixed
