### ISSUE TITLE
serverStats don't work

### ISSUE THREAD

**Issue by DanielMarkink** [ChimpGamer/NetworkManager#17]
### What steps do you need to take to reproduce the problem?  
1.  Download and install the serverStats addon.
2. Go in the panel to the serverStats addon page.
3. Now it will say: **loading** but never show the stats.

### What were you expecting to happen? What happens instead?  
Show the stats.

### Did you tried to reproduce the problem on a clean environment?  
Yes

### What version of the plugin are you using? (Type /networkmanager (In-Game))  
not needed

### What BungeeCord/Spigot version are you using? (Type /bungee for BungeeCord and /version for Spigot)  
Not needed

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com), [pastebin.com](http://pastebin.com) or insert a screenshot.
https://pastebin.com/TtkJ2H2i

**Comment by DanielMarkink** [comment]
Error:
loaded page
core.js:4:9
SyntaxError: expected expression, got '}'[Meer info]
dashboard.php:66:44
loaded page
core.js:17:17

**Comment by ChimpGamer** [comment]
Solved all issues!
