### ISSUE TITLE
Motd will not show in the example

### ISSUE THREAD

**Issue by DanielMarkink** [ChimpGamer/NetworkManager#18]
### What steps do you need to take to reproduce the problem?  
1. Go to the "MOTD" setting
2. Look at the example

### What were you expecting to happen? What happens instead?  
Show the MOTD

### Did you tried to reproduce the problem on a clean environment?  
Yes

### What version of the plugin are you using? (Type /networkmanager (In-Game))  
2.2.4.1

### What BungeeCord/Spigot version are you using? (Type /bungee for BungeeCord and /version for Spigot)  
BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:968916c:1316

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com), [pastebin.com](http://pastebin.com) or insert a screenshot.
Uncaught TypeError: yourMOTD.replaceColorCodes is not a function
    at <anonymous>:19:36

**Comment by Evesain** [comment]
remove this plugin :D https://dev.bukkit.org/projects/yourmotd
then try again, and the stacktrace error literally just shows an error from that plugin, nothing to do with networkmanager

**Comment by ChimpGamer** [comment]
It's a JS error that comes from the Web Interface and should have been fixed in one of the latest version of the Web Interface.
