### ISSUE TITLE
Maintance kick message don't get displayed.

### ISSUE THREAD

**Issue by DanielMarkink** [ChimpGamer/NetworkManager#19]
### What steps do you need to take to reproduce the problem?  
1. Enable all settings.
2. Reload all networkmanager/networkmanagerbridge or restart all servers
3. Join the server.

### What were you expecting to happen? What happens instead?  
Give me the maintance message.

### Did you tried to reproduce the problem on a clean environment?  
Yes

### What version of the plugin are you using? (Type /networkmanager (In-Game))  
2.2.4.1

### What BungeeCord/Spigot version are you using? (Type /bungee for BungeeCord and /version for Spigot)  
BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:968916c:1316

### Any additional information that might be useable/important?
I get as message in my minecraft.

**Internal Exception: java.io.IOException: De externe host heeft een verbinding verbroken**

**Comment by Evesain** [comment]
Have you tried updating?

**Comment by DanielMarkink** [comment]
I am running the latest version now.
But i have still that bugg :(

**Comment by DanielMarkink** [comment]
It seems fixed by now.
