### ISSUE TITLE
Commandblocker problem

### ISSUE THREAD

**Issue by DanielMarkink** [ChimpGamer/NetworkManager#2]
### What steps do you need to take to reproduce the problem?  
1. Add an command to the commandblocker.
2. Make sure that you don't have the bypass permission
3. do "<blockedcommand>" and add an arg.
4. now you have bypass the commandblocker without permission.

### What were you expecting to happen? What happens instead?  
Block the command from using.

### What version of the plugin are you using? (Type /networkmanager (In-Game))  
![6](https://user-images.githubusercontent.com/30463195/35825410-07c2b81e-0ab6-11e8-99a6-3678b9ea8a8a.PNG)

### What BungeeCord/Spigot version are you using? (Type /bungee for BungeeCord and /version for Spigot)  
![8](https://user-images.githubusercontent.com/30463195/35825428-13712844-0ab6-11e8-94ec-f08af755a32f.PNG)
![7](https://user-images.githubusercontent.com/30463195/35825430-138f9c0c-0ab6-11e8-8860-f29d2d4d91ab.PNG)

**Comment by DanielMarkink** [comment]
Still not fix :(
![3](https://user-images.githubusercontent.com/30463195/35867676-acd0d10c-0b5a-11e8-8a92-b7b6226d24fa.PNG)
![1](https://user-images.githubusercontent.com/30463195/35867678-ad13360a-0b5a-11e8-83da-4997d0013013.PNG)
![2](https://user-images.githubusercontent.com/30463195/35867679-ad3e0cea-0b5a-11e8-9609-6139f959257f.PNG)

**Comment by ChimpGamer** [comment]
Should be fixed in the new Update NetworkManager 2.1.0
