### ISSUE TITLE
AdminChat don't work

### ISSUE THREAD

**Issue by DanielMarkink** [ChimpGamer/NetworkManager#21]
### What steps do you need to take to reproduce the problem?  
1. Change in the settings "command_adminchat" from adminchat to helperchat
2. Change in the settings "command_adminchat_alias" from ac to hc
3. Restart all spigot server and the bungeecord.
4. Check if you have the permission to use it.
5. Do ingame /helperchat toggle
6. Type something in the chat.

### What were you expecting to happen? What happens instead?  
Send the message and give no error

### Did you tried to reproduce the problem on a clean environment?  
Yes

### What version of the plugin are you using? (Type /networkmanager (In-Game))  
![1](https://user-images.githubusercontent.com/30463195/41701023-0d8f1e2e-752b-11e8-84fa-4ea6289a50f6.PNG)

### What BungeeCord/Spigot version are you using? (Type /bungee for BungeeCord and /version for Spigot)  
![2](https://user-images.githubusercontent.com/30463195/41701047-2548d14a-752b-11e8-946a-a8efeb60eab0.PNG)
![3](https://user-images.githubusercontent.com/30463195/41701065-3a4dbeb6-752b-11e8-825c-0f89ac6d8969.PNG)

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com), [pastebin.com](http://pastebin.com) or insert a screenshot.
https://pastebin.com/x0RBB0gY

**Comment by DanielMarkink** [comment]
Will be fixed in the next update

**Comment by ChimpGamer** [comment]
Fixed in latest update!
