### ISSUE TITLE
MOTD is not displayed when maintance motd is enabled.

### ISSUE THREAD

**Issue by DanielMarkink** [ChimpGamer/NetworkManager#24]
### What steps do you need to take to reproduce the problem?  
1. Enable maintance.
2. Restart bungeecord

### What were you expecting to happen? What happens instead?  
Show the MOTD

### Did you tried to reproduce the problem on a clean environment?  
Yes

### What version of the plugin are you using? (Type /networkmanager (In-Game))  
2.5.0

### What BungeeCord/Spigot version are you using? (Type /bungee for BungeeCord and /version for Spigot)  
This server is running BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:ceb9ea1:1329 by md_5

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com), [pastebin.com](http://pastebin.com) or insert a screenshot.
no errors

### Any additional information that might be useable/important?
This issue also was in 2.4.3
![1](https://user-images.githubusercontent.com/30463195/45590632-ec64b780-b93c-11e8-892a-769f7819074a.PNG)

**Comment by DanielMarkink** [comment]
And i can join the server just fine.

**Comment by ChimpGamer** [comment]
![image](https://user-images.githubusercontent.com/19960733/45624356-6fdfef00-ba8a-11e8-84b3-0bc021045c77.png)
![image](https://user-images.githubusercontent.com/19960733/45624363-72dadf80-ba8a-11e8-967c-91e12231fc66.png)

I didn't even restarted the server.
