### ISSUE TITLE
Ticket system Malfuntion

### ISSUE THREAD

**Issue by cdmvirt** [ChimpGamer/NetworkManager#25]
### What steps do you need to take to reproduce the problem?  
1. Create a Ticket in-game

### What were you expecting to happen? What happens instead?  
Says ticket was created with the ID, but doesnt actually create it.

### Did you tried to reproduce the problem on a clean environment?  
Yes

### What version of the plugin are you using? (Type /networkmanager (In-Game))  
2.50
### What BungeeCord/Spigot version are you using? (Type /bungee for BungeeCord and /version for Spigot)  
Paper/Spigot

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com), [pastebin.com](http://pastebin.com) or insert a screenshot.
https://hastebin.com/hujiqevipe.shell <---Bungeecord

**Comment by ChimpGamer** [comment]
The stacktrace link shows a empty text

**Comment by ChimpGamer** [comment]
--No respond--
