### ISSUE TITLE
Networkmanager Web Litebans addon

### ISSUE THREAD

**Issue by mesl** [ChimpGamer/NetworkManager#27]
### What steps do you need to take to reproduce the problem?  
1. Install NetworkManager Web & Plugin
2. Install the Litebans addon
3. Check the bans/mutes Etc in the Litebans addon tab
etc.

### What were you expecting to happen? What happens instead?  
I expected to see the punishments but instead, I didn't saw any punishments

### Did you tried to reproduce the problem on a clean environment?  
Yes

### What version of the plugin are you using? (Type /NetworkManager (In-Game))  
2.5.1

### What BungeeCord/Spigot version are you using? (Type /bungee for BungeeCord and /version for Spigot)  

Spigot = Final 1.12.2 Build
Bungee = BungeeCord-Bootstrap:1.13-SNAPSHOT:bba5098:1358

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com), [pastebin.com](http://pastebin.com) or insert a screenshot.
Not afaik

### Any additional information that might be useable/important?
The servers and databases run in docker surroundings

**Comment by ChimpGamer** [comment]
![image](https://user-images.githubusercontent.com/19960733/48354307-a6547780-e691-11e8-95c2-7e02e2359f29.png)

I've no idea what's wrong.

**Comment by mesl** [comment]
![image](https://user-images.githubusercontent.com/10009454/48473609-192c3280-e7f9-11e8-93ee-aed563add574.png)
This is all I see

**Comment by DanielMarkink** [comment]
@mesl do you have any punishmets?
(Kicked, baed, ect an player?)

**Comment by mesl** [comment]
Yes I do have punishments and they are in my database (already checked that)

**Comment by ChimpGamer** [comment]
No response
