### ISSUE TITLE
Can't use SSL

### ISSUE THREAD

**Issue by DanielMarkink** [ChimpGamer/NetworkManager#28]
### What steps do you need to take to reproduce the problem?  
1. Add an working SSL to the mysql server.
2. Enter the information into the settings.yml of networkmanager.
3. Add after the databasename: ?usessl=true

### What were you expecting to happen? What happens instead?  
Work instead of saying cannot conntect. And start using the SSL.

### Did you tried to reproduce the problem on a clean environment?  
Yes

### What version of the plugin are you using? (Type /networkmanager (In-Game))  
2.5.2

### What BungeeCord/Spigot version are you using? (Type /bungee for BungeeCord and /version for Spigot)  
18.11 10:59:31 [Server] INFO This server is running BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:ceb9ea1:1329 by md_5

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com), [pastebin.com](http://pastebin.com) or insert a screenshot.
18.11 10:54:20 [Server] INFO [NetworkManager] Creating HikariCP Configuration...
18.11 10:54:20 [Server] INFO [NetworkManager] Setting up MySQL Connection pool...
18.11 10:54:20 [Server] SEVERE [main] INFO com.zaxxer.hikari.HikariDataSource - networkmanager-pool - Starting...
18.11 10:54:20 [Server] SEVERE [main] INFO com.zaxxer.hikari.HikariDataSource - networkmanager-pool - Start completed.
18.11 10:54:20 [Server] INFO [NetworkManager] Connection pool successfully configured.
18.11 10:54:20 [Server] INFO [NetworkManager] Creating tables...
18.11 10:54:25 [Server] INFO [NetworkManager] Failed to create tables: networkmanager-pool - Connection is not available, request timed out after 5001ms.
18.11 10:54:25 [Server] INFO [NetworkManager] |  Plugin disabled Could not connect with MySQL
18.11 10:54:25 [Server] INFO Enabled plugin NetworkManager version 2.5.2 by Dunios & ChimpGamer

**Comment by ChimpGamer** [comment]
Solved?
