### ISSUE TITLE
Default lang_report_alert_jump -message is only clickable on the last character.

### ISSUE THREAD

**Issue by PsychoLynx** [ChimpGamer/NetworkManager#29]
### What steps do you need to take to reproduce the problem?  
1. Report a player as A
2. As admin account B, receive the REPORT notification including "Click here to jump to the server of the report!"
3. Only the last character "<<" is clickable. The rest of the text isn't.

### What were you expecting to happen? What happens instead?  
The whole text to be clickable

### Did you tried to reproduce the problem on a clean environment? 
No, but my test server is fairly clean.

### What version of the plugin are you using? (Type /networkmanager (In-Game))  
2.6.6.1

### What BungeeCord/Spigot version are you using? (Type /bungee for BungeeCord and /version for Spigot)  
Waterfall build 279

**Comment by ChimpGamer** [comment]
Are you using RedisBungee?

**Comment by PsychoLynx** [comment]
I am not

**Comment by PsychoLynx** [comment]
Fixed with the latest update.
