### ISSUE TITLE
Luckyperms loading

### ISSUE THREAD

**Issue by Kstuard** [ChimpGamer/NetworkManager#30]
### What steps do you need to take to reproduce the problem?  
1. luckyperms
2. 
3. 
etc.

### What were you expecting to happen? What happens instead?  
to change permissions and its keep loading 

### Did you tried to reproduce the problem on a clean environment?  
yes
### What version of the plugin are you using? (Type /networkmanager (In-Game))  
2.7.9.1
### What BungeeCord/Spigot version are you using? (Type /bungee for BungeeCord and /version for Spigot)  
by md_5

**Comment by Kstuard** [comment]
and dont work any permissions like i tryed permissions from network manager and after from luckperms and nothing happeneds

**Comment by ChimpGamer** [comment]
I have no idea what this is about. Is it about the LuckPerms addon or is it about networkmanager permissions in LuckPerms?

**Comment by ChimpGamer** [comment]
-No response-
