### ISSUE TITLE
Espanol.php file is empy (in my case)

### ISSUE THREAD

**Issue by goku727** [ChimpGamer/NetworkManager#31]
### What steps do you need to take to reproduce the problem?  
1. Dowload webinterface from discord
2. Install it
3. Change default language to spanish

### What were you expecting to happen? What happens instead?  
Everything is empty and only the icons are seen , instead of change to spanish languaje
### Did you tried to reproduce the problem on a clean environment?  
I re-instalate all web interface minus the database in my machine
### What version of the plugin are you using? (Type /networkmanager (In-Game))  
2.8.0
### What BungeeCord/Spigot version are you using? (Type /bungee for BungeeCord and /version for Spigot)  
git:Waterfall-Bootstrap:1.14-SNAPSHOT:9e17ca3:294
### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com), [pastebin.com](http://pastebin.com) or insert a screenshot.
No
### Any additional information that might be useable/important?
https://youtu.be/hqiQgwZ3lZU

**Comment by ChimpGamer** [comment]
Make sure you have:
1. The correct file permissions applied to "inc/php/dep/language".
2. Installed cURL and the php cURL expansion.

**Comment by goku727** [comment]
I copy the content of English.php to Espanol.php an when i change languaje, webinterface have all (in English) but its not empy

**Comment by ChimpGamer** [comment]
Can you confirm php_curl is actually enabled when using phpinfo?

**Comment by goku727** [comment]
![image](https://user-images.githubusercontent.com/34101063/65268710-06207800-db18-11e9-8c7d-8e1dc08e6243.png)

**Comment by ChimpGamer** [comment]
Then the language file might be the problem. It hasn't been updated in a year. Feel free to update it if you want!

**Comment by goku727** [comment]
Okey, thanks. 
I open this issue because I have seen that more people had this problem.
