### ISSUE TITLE
Server Manager Issues

### ISSUE THREAD

**Issue by GameHoundInteractive** [ChimpGamer/NetworkManager#32]
### What steps do you need to take to reproduce the problem?  
1. join a network
2. 
3. 
etc.

### What were you expecting to happen? What happens instead?  
i was expecting it to always send me to hub on join. / send me to hub when server im on goes down. 

Basicly it sends u to last known server 50% of the time and never sends u to hub when server goes down. 
### Did you tried to reproduce the problem on a clean environment?  
yes
### What version of the plugin are you using? (Type /networkmanager (In-Game))  
Version » v2.8.0
### What BungeeCord/Spigot version are you using? (Type /bungee for BungeeCord and /version for Spigot)  
 This server is running Waterfall version git:Waterfall-Bootstrap:1.14-SNAPSHOT:9e17ca3:294 by md_5
### Any additional information that might be useable/important?
https://prnt.sc/pi6oqy

**Comment by ChimpGamer** [comment]
disable force_default_server in the config.yml of BungeeCord.

**Comment by GameHoundInteractive** [comment]
It is disabled

**Comment by GameHoundInteractive** [comment]
https://prnt.sc/picj0n

**Comment by ChimpGamer** [comment]
Then the server group name is perhaps invalid. Check bungeecord log when you join.




Outlook voor Android downloaden







On Sat, Oct 12, 2019 at 4:37 PM +0200, "GHStudios" <notifications@github.com> wrote:












https://prnt.sc/picj0n

**Comment by GameHoundInteractive** [comment]
Its not, I already checked. It also constantly says server has came online or offline when the state of server has not changed.

**Comment by ChimpGamer** [comment]
That sounds like a latency issue :/. Ping me on Discord so we can take a look at it together.
