### ISSUE TITLE
Can't open /tags 

### ISSUE THREAD

**Issue by Golicraft** [ChimpGamer/NetworkManager#34]
### What steps do you need to take to reproduce the problem?  
1. Latest versions of both Network Manager and Tags
2. Be on 1.8 to 1.15.2
3. Type /tags
etc.

### What were you expecting to happen? What happens instead?  
It doesn't show up the menu and it says in chat "internal error bla bla bla" xD

### Did you tried to reproduce the problem on a clean environment?  
No

### What version of the plugin are you using? (Type /networkmanager (In-Game))  
Latest version

### What BungeeCord/Spigot version are you using? (Type /bungee for BungeeCord and /version for Spigot)  
I use spigot 1.12.2

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com), [pastebin.com](http://pastebin.com) or insert a screenshot.
Yes. https://pastebin.com/xLFhTcU3

### Any additional information that might be useable/important?
It worked on previous versions. This happend after I updated my server.

**Comment by ChimpGamer** [comment]
You're missing the showNoAccessItems option in the tags menu. Make sure the tagsmenu.json is valid.
