### ISSUE TITLE
Error Punishment 

### ISSUE THREAD

**Issue by underoworkd12** [ChimpGamer/NetworkManager#36]
### What steps do you need to take to reproduce the problem?  
1. 
2. 
3. 

### What were you expecting to happen? What happens instead?  I can’t give ban ,
because it tells me that this user is not in the database

### Any additional information that might be useable/important?

**Comment by ChimpGamer** [comment]
First of all you're on an outdated version of the plugin which makes this issue invalid. Second the player needs to join the server atleast once so the plugin has some information about the player.
