### ISSUE TITLE
Alert staff when a player with the same IP as a banned player joins the game

### ISSUE THREAD

**Issue by MCAlagaesia** [ChimpGamer/NetworkManager#37]
All players with a permission (such as `networkmanager.notify.joinbanned.alt`) get a message in the chat when a player with the same IP as a banned player joins the network.

e.g:
```
player_one joined the game
player_one has the same IP as the banned player player_two
```

**Comment by ChimpGamer** [comment]
Added this feature in the latest build of NetworkManager available in the NetworkManager Discord server. This feature is not configurable yet! Please let me know if it works as intended.

**Comment by MCAlagaesia** [comment]
I haven't yet updated (waiting on some other 1.16 updates), but I'll take a look when I do.

**Comment by MCAlagaesia** [comment]
What's the permission node for this?
