### ISSUE TITLE
Coloured names in the tab list.

### ISSUE THREAD

**Issue by MCAlagaesia** [ChimpGamer/NetworkManager#39]
**Is your feature request related to a problem? Please describe.**
NetworkManager already has the ability to make the tab list pretty, but the one thing that remains boring is the player names.

**Describe the solution you'd like**
Allow coloured names in the tab list.
This could be defined by permissions similar to the existing `networkmanager.color.x` permissions.
For example, giving a group the `networkmanager.color.tab.red` would give users in that group a red name in the tab list.

Example:
![image](https://user-images.githubusercontent.com/10643460/86234510-5f0a5a00-bbda-11ea-8b16-b16cacf7ac6d.png)

**Comment by Arlind-A** [comment]
Adding onto this, it could be better if it was made so that each group can get a prefix and suffix added so we can have rank names in the tab along with something else in the suffix. Of course this should support placeholderapi so we could add placeholders outside of NetworkManager. Also the name changes on tablist should appear ingame above the players head.

Also ranking the names in tab in order according to the group a player is in and the weight/rank of the group they are in.

**Comment by ChimpGamer** [comment]
> Adding onto this, it could be better if it was made so that each group can get a prefix and suffix added so we can have rank names in the tab along with something else in the suffix. Of course this should support placeholderapi so we could add placeholders outside of NetworkManager. Also the name changes on tablist should appear ingame above the players head.
> 
> Also ranking the names in tab in order according to the group a player is in and the weight/rank of the group they are in.

Don't think it is possible to do that with the spigot-api.

**Comment by Arlind-A** [comment]
the TAB plugin does something similar to this. The bungeecord jar controls all the server tabs and it uses a bridging method to allow PAPI to be used getting them from the spigot servers itself.

**Comment by Arlind-A** [comment]
> > Adding onto this, it could be better if it was made so that each group can get a prefix and suffix added so we can have rank names in the tab along with something else in the suffix. Of course this should support placeholderapi so we could add placeholders outside of NetworkManager. Also the name changes on tablist should appear ingame above the players head.
> > Also ranking the names in tab in order according to the group a player is in and the weight/rank of the group they are in.
> 
> Don't think it is possible to do that with the spigot-api. But I'll check it out.

the TAB plugin does something similar to this. The bungeecord jar controls all the server tabs and it uses a bridging method to allow PAPI to be used getting them from the spigot servers itself.

**Comment by ChimpGamer** [comment]
I release an extension of it in #beta-builds in the Discord server.
