### ISSUE TITLE
Can't change time format.

### ISSUE THREAD

**Issue by DanielMarkink** [ChimpGamer/NetworkManager#4]
### What steps do you need to take to reproduce the problem?  
1. Go to "Settings".
2. Go to webinterface.
3. Change the time display.
4. And reload the browser.
5. And there you have your not changed time format to the settings.

### What were you expecting to happen? What happens instead?  
Change to the new time format display.

### What version of the plugin are you using? (Type /networkmanager (In-Game))  
![1](https://user-images.githubusercontent.com/30463195/35876259-0823c50c-0b72-11e8-9cd2-f5f66ae9f141.PNG)

### What BungeeCord/Spigot version are you using? (Type /bungee for BungeeCord and /version for Spigot)  
![2](https://user-images.githubusercontent.com/30463195/35876267-0b7ff3b0-0b72-11e8-83f4-c66e5af2560b.PNG)
![3](https://user-images.githubusercontent.com/30463195/35876268-0ba272a0-0b72-11e8-9d92-f1f43aff8361.PNG)

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com) or [pastebin.com](http://pastebin.com).
![4](https://user-images.githubusercontent.com/30463195/35876377-5b49ce5c-0b72-11e8-9203-7137732b3175.PNG)

**Comment by ChimpGamer** [comment]
It does change but it does not effect some pages. Please tell what pages and I will take a look into it.

**Comment by DanielMarkink** [comment]
i have it with all pages :(

**Comment by DanielMarkink** [comment]
Still not fix :(

**Comment by DanielMarkink** [comment]
Fix:
Open the header.php and change: "document.getElementById('clockbox').innerHTML = "" + nhour + ":" + nmin + ":" + nsec + "";" -> "document.getElementById('clockbox').innerHTML = "" + nhour + ":" + nmin + "";"
