### ISSUE TITLE
View more chat messages

### ISSUE THREAD

**Issue by MCAlagaesia** [ChimpGamer/NetworkManager#42]
**Is your feature request related to a problem? Please describe.**
Only being able to see 10 messages at a time isn't really good enough. There's also no way to skip ahead more than 1 page at a time, making it really slow to try and get to anything older than a couple of hours.

![image](https://user-images.githubusercontent.com/10643460/86236041-bd383c80-bbdc-11ea-970a-c8494f47affb.png)

**Describe the solution you'd like**
There are a couple of things that could be done to improve this:
Show 100 messages per page, and allow the user to skip more than one page or enter a custom page number

or

Infinite scroll (lazy load another 100 older messages when you scroll down far enough).

**Comment by MCAlagaesia** [comment]
The same feature could be implemented for other lists in the Webbie, such as the punishments list, players list, permissions list and groups list.

**Comment by ChimpGamer** [comment]
In the new web interface it is now possible to select the amount of entries per page which solves this issue.
