### ISSUE TITLE
Show player groups in player information

### ISSUE THREAD

**Issue by MCAlagaesia** [ChimpGamer/NetworkManager#43]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to see what groups a player is a member of from the Webbie (instead, you have to run `/nmpb user {username}` in-game).

**Describe the solution you'd like**
Add a list of the player's groups to the player information page. For example:
![image](https://user-images.githubusercontent.com/10643460/86237181-a397f480-bbde-11ea-8eca-85f856c517d4.png)

**Comment by ChimpGamer** [comment]
This has sort of  been taken care of. In the new web interface you can see which groups a player has on the permissions page.
![image](https://github.com/ChimpGamer/NetworkManager/assets/19960733/1e6a0fd4-3a0f-4d55-a20c-48a32b26c13d)
