### ISSUE TITLE
Not moving players to fallback uppon server stop

### ISSUE THREAD

**Issue by DomiiBunn** [ChimpGamer/NetworkManager#45]
Players are kicked on server restart 1.16.1 only

**Steps To Reproduce**
Create a proxy, a hub/fallback server and a game server on latest versions
enable server control and fallback servers
Join the server
join the game server
Stop The server
Player gets kicked

**Expected behaviour**
Player gets moved to the fallback server

**Stack Trace**
No errors but might be usefull
Bungiee
```
01:01:07 [INFO] [DomiiBunn,/000.000.000.000:50834] <-> InitialHandler has connected
01:01:07 [INFO] [DomiiBunn] <-> ServerConnector [Hub1] has connected
01:01:45 [INFO] [000.000.000.000] <-> InitialHandler has connected
01:02:03 [INFO] [DomiiBunn] <-> ServerConnector [Survival] has connected
01:02:15 [INFO] [DomiiBunn] <-> DownstreamBridge <-> [Hub1] has disconnected
01:02:20 [INFO] [DomiiBunn] disconnected with: [Proxy] Lost connection to server.
01:02:20 [INFO] [DomiiBunn] <-> DownstreamBridge <-> [Survival] has disconnected
01:02:20 [INFO] [DomiiBunn] -> UpstreamBridge has disconnected```
```
Server 
```
[01:06:53] [User Authenticator #1/INFO]: UUID of player DomiiBunn is 993b7c94-d406-4d36-ac0d-586318ee740b
[01:06:54] [Server thread/INFO]: DomiiBunn[/84.148.212.119:55899] logged in with entity id 192 at ([world]-2937.5, 69.0, 196.5)
[01:06:58] [Server thread/INFO]: DomiiBunn issued server command: /stop
[01:06:58] [Server thread/INFO]: [DomiiBunn: Stopping the server]
[01:06:58] [Server thread/INFO]: Stopping server
```

**Version Information:**
 - NetworkManager:
```
>networkmanager about
01:18:29 [INFO] Developers » ChimpGamer
01:18:29 [INFO] Version » v2.8.9-SNAPSHOT
01:18:29 [INFO] Buyer of this plugin » https://www.SpigotMC.org/members/\%%__USER__%%\
01:18:29 [INFO] UniqueDownloadId » \%%__NONCE__%%\
01:18:29 [INFO] Wiki » https://github.com/ChimpGamer/NetworkManager/wik
```
 - Spigot/Paper: `Server: Spigot 1.16.1-R0.1-SNAPSHOT`
 - Bungee/Waterfall/Proxy: `BungeeCord version git:BungeeCord-Bootstrap:1.16-R0.2-SNAPSHOT:4794fcc:1521 by md_5`
**Additional context**
Posted in discord as well https://discordapp.com/channels/222070253172031500/227773525006614540/729866240990117918

![image](https://user-images.githubusercontent.com/51760394/86682529-f6b7e000-c000-11ea-925f-835679c36086.png)

**Comment by ChimpGamer** [comment]
@DomiiBunn Did you managed to figure out what the problem is because I can't reproduce it.

**Comment by DomiiBunn** [comment]
Didn't figure it out...If you want you can ping me in discord and i can give you all perms :)

**Comment by ChimpGamer** [comment]
Does this issue still persist in the latest version? Please let me know.

**Comment by ChimpGamer** [comment]
No response. Guess it's solved then.
