### ISSUE TITLE
Bug - Player Information

### ISSUE THREAD

**Issue by Grover478** [ChimpGamer/NetworkManager#46]
https://prnt.sc/tj2o03 - Error by openting the Player statistic

**Comment by ChimpGamer** [comment]
First of all the format of this issue is invalid. Second, I can't reproduce this issue with PHP 7.3 and MariaDB 10.3.21 (MariaDB is a fork of MySQL). Maybe this will help you solve your issue: https://stackoverflow.com/a/51629259
