### ISSUE TITLE
Playtime don't change

### ISSUE THREAD

**Issue by DanielMarkink** [ChimpGamer/NetworkManager#5]
### What steps do you need to take to reproduce the problem?  
1. do tab on you key bord and see that he playtime don't change.

### What were you expecting to happen? What happens instead?  
Update the playtime.

### What version of the plugin are you using? (Type /networkmanager (In-Game))  
![1](https://user-images.githubusercontent.com/30463195/36073147-004c99e0-0f2c-11e8-8521-903c08934220.PNG)

### What BungeeCord/Spigot version are you using? (Type /bungee for BungeeCord and /version for Spigot)  
![3](https://user-images.githubusercontent.com/30463195/36073149-0981a992-0f2c-11e8-9b73-97768a4f937a.PNG)
![2](https://user-images.githubusercontent.com/30463195/36073150-0999f93e-0f2c-11e8-8336-b9bd547c80ec.PNG)

**Comment by ChimpGamer** [comment]
Didn't you find any stacktrace error's? Do you have any screenshots? Tablist, /playtime, WebInterface, etc?

**Comment by ChimpGamer** [comment]
Should be fixed. If not open a new issue!
