### ISSUE TITLE
PrePunishment Time not working

### ISSUE THREAD

**Issue by TheRemiDev** [ChimpGamer/NetworkManager#54]
**Describe the bug**
Pre-Punishment with temporary durations does not work. 

**Steps To Reproduce**
Steps to reproduce the behaviour:
1. Create a Pre-Punishment on the web manager. Put a temporary penalty, for example, a temporary global ban. Put a duration of 30000, the sanction applied in game with the command /punish [player] [id] will only apply the sanction for one second.

**Screenshots**

1. https://s.theremidev.fr/yy9rcix6.png
2. https://s.theremidev.fr/rj0wleoc.png

**Version Information:**
 - NetworkManager: https://s.theremidev.fr/dlx9yums.png
 - Spigot/Paper: https://s.theremidev.fr/xtzsdb9j.png
 - Bungee/Waterfall/Proxy: https://s.theremidev.fr/n8qx04rv.png

**Comment by ChimpGamer** [comment]
You've set the duration to 30 milliseconds. In-game that will be rounded up to 1 second.
See (https://s.theremidev.fr/rj0wleoc.png)

**Comment by ChimpGamer** [comment]
No response.
