### ISSUE TITLE
can't hook into PremiumVanish

### ISSUE THREAD

**Issue by Qw4rtz** [ChimpGamer/NetworkManager#55]
**Describe the bug**
On loading, NetworkManager can't hook into PremiumVanish. However, it does not stop NetworkManager which responds fine to commands afterward.

**Steps To Reproduce**
1. Start the proxy.
2. Watch the console.

**Expected behaviour**
It should've hooked correctly.

**Stack Trace**
https://pastebin.com/3BvhgcHX

**Version Information:**
 - NetworkManager: 2.8.9.3
 - PremiumVanish: 2.5.19
 - Bungee/Waterfall/Proxy: [FlameCord](https://www.mc-market.org/resources/13492/) 0.4.2

**Comment by ChimpGamer** [comment]
Have you already tried to redownload NetworkManager and/or PremiumVanish because it works just fine for me on Waterfall.

**Comment by Qw4rtz** [comment]
I just tested with Waterfall #379, to see if it had something to do with FlameCord, then I re-added plugins one by one and found that it only happens with [ajQueuePlus](https://www.spigotmc.org/resources/ajqueueplus.79123).

I tested with only NetworkManager, PremiumVanish and ajQueuePlus and still get that error. I also only get the error when both PremiumVanish and ajQueuePlus are there.

**Comment by ChimpGamer** [comment]
I don't know what ajQueuePlus does with PremiumVanish.

**Comment by Qw4rtz** [comment]
My issue was solved when updating to ajQueuePlus v1.6.10-pre4 (being a beta/pre-release, it's only available on aj's Discord). NetworkManager doesn't give any error anymore. Thank you for your time :)
