### ISSUE TITLE
NM Discord Bot

### ISSUE THREAD

**Issue by TheRemiDev** [ChimpGamer/NetworkManager#56]
Hello, 

My proposal today is for NMDiscordBot. I wanted to propose that in the next update it will be possible to add several Discord roles with a single MC role.

**Comment by ChimpGamer** [comment]
This is possible in the current version of the DiscordBot.
You can define the rank multiple times with a different role.
For example:
ranks:
    enabled: false
    map:
        rank1: role1
        rank2: role2
        rank1: role3

This will give the player role1 and role3 if they have rank1.
