### ISSUE TITLE
Custom response per command in the command blocker module

### ISSUE THREAD

**Issue by MCAlagaesia** [ChimpGamer/NetworkManager#58]
**Is your feature request related to a problem? Please describe.**
The command blocker module uses the same `lang_commandblocked_isblocked` for every command that is blocked.

**Describe the solution you'd like**
Ability to set a custom response per command in the CommandBlocker module, so one can send the user a more informative message about why their access to a particular command was blocked.

For example, you could tell a user:
`You need to run this command in the lobby. Use "/hub" to get to the lobby.` when they try a hub-specific command.
`Unknown command. Type "/help" for help.` when they try an admin command that you don't want to reveal exists by sending a block message.

**Describe alternatives you've considered**

**Additional context**
This is an old request from Discord, but it didn't go through the bot.
https://discordapp.com/channels/222070253172031500/341357067619139585/662179132792373268

**Comment by ChimpGamer** [comment]
I think that's a great idea. I'll try to get it done in the 2.9.0 update.

**Comment by ChimpGamer** [comment]
I just noticed that this has already been implemented in the plugin. There is just no field to fill in a message in the Web Interface right now. This should be added in the new Web Interface (version 3.0)

**Comment by MCAlagaesia** [comment]
That's fantastic, thanks!
