### ISSUE TITLE
Incorrect player shown in non-configurable message

### ISSUE THREAD

**Issue by MCAlagaesia** [ChimpGamer/NetworkManager#59]
**Describe the bug**
Alt account detector sends the message `Player banned_player joined but has an alt (banned_player) that is banned (ban_type)`
(It says that the banned player joined rather than saying a new player joined)

**Steps To Reproduce**
1. Join with an administrator account (someone who has the ability to see these messages, but I have no idea what the permission node for these messages is)
2. Ban an account
3. Join the server with a new account on the same network (same IP) as the banned account.

**Expected behaviour**
Show the message `Player player joined but has an alt (banned_player) that is banned (ban_type)` or allow the message to be configured in languages

**Screenshots**
![image](https://user-images.githubusercontent.com/10643460/98649683-f7d09380-238b-11eb-828e-f5ef25d1aa0b.png)

**Version Information:**
 - NetworkManager: Version » v2.8.9.3
 - Spigot/Paper: git-Paper-265 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
 - Bungee/Waterfall/Proxy: Waterfall version git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:1d2221d:384

**Additional context**
Related to #37

**Comment by ChimpGamer** [comment]
This should have been fixed in the 2.9.0 beta version.

**Comment by MCAlagaesia** [comment]
Can confirm, looks good!
