### ISSUE TITLE
CloudNet v3 Implementation

### ISSUE THREAD

**Issue by HaxHead** [ChimpGamer/NetworkManager#63]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I want an CloudNet v3 implementation. So that ranks are displayed in the User Overview Tab a Server Management Tab to start stop Services and create new tasks (and edit) maybe with a server Console but not important. Also a part to configure the Sign System and the Permission System of Cloudnet but for maybe a Beta Build the Ranks in the Player Overview would be very nice.

**Describe alternatives you've considered**
--

**Additional context**
--

**Comment by HaxHead** [comment]
and for CloudNet v2 also please. I would prefer at this time the v2 Version

**Comment by ChimpGamer** [comment]
I would suggest you modify the web interface to your liking since the amount of users that use NetworkManager and CloudNet at the same time is pretty slim.
