### ISSUE TITLE
Better Multiaccount IP Ban Information and Messages

### ISSUE THREAD

**Issue by WilliDieEnte** [ChimpGamer/NetworkManager#70]
Right now, if somebody who is IP-Banned tries to join, a message like this is shown: » Account1 tried to join, but is banned.
But If I join with another Account from the Same IP it still says the same.
It would be nice if another Account joins from That IP that a message like » Account2 tried to join, but has the same IP as Account1 which is banned.

**Comment by MCAlagaesia** [comment]
I think what you're asking is already implemented.

https://github.com/ChimpGamer/NetworkManager/issues/37
https://github.com/ChimpGamer/NetworkManager/issues/59
