### ISSUE TITLE
Tweaking permission system for more flexible use

### ISSUE THREAD

**Issue by CraftJunkies** [ChimpGamer/NetworkManager#74]
Feature to allow a player to promote on a specific permission ladder only

**Comment by Craftsman96** [comment]
I meant to allow with permission node player a to promote only on ladder a and player b with permission b only Other Players on ladder b

**Comment by Craftsman96** [comment]
So ladders could be used as complete permission subsystems

**Comment by ChimpGamer** [comment]
That's not the purpose of ladders

**Comment by Craftsman96** [comment]
So Situation i host another server and they can use there ladder as complete permission system and add ranks and permissions but only to there own ladder

**Comment by Craftsman96** [comment]
Then add complete subsystems to permissions

**Comment by ChimpGamer** [comment]
If you want that I would suggest you use LuckPerms with different databases.

**Comment by Craftsman96** [comment]
Problem with luckperms is that all runs behind the Proxy With nmw

**Comment by Craftsman96** [comment]
So i See Problems when using 2 systems and yours is better than luckperms

**Comment by ChimpGamer** [comment]
You can use LuckPerms on these servers behind a proxy just fine in standalone mode.

**Comment by Craftsman96** [comment]
Ok didnt know its possible. And proxy is still save when lp isnt installed on Proxy ?

**Comment by ChimpGamer** [comment]
I never use LuckPerms but I'm pretty sure you can do very complex things with it.
