### ISSUE TITLE
NMW API

### ISSUE THREAD

**Issue by Craftsman96** [ChimpGamer/NetworkManager#77]
Public API documentation For devs to write Plugins and Extensions for nmw

**Comment by ChimpGamer** [comment]
No sure what NMW means but https://networkmanager.gitbook.io/wiki/networkmanager-plugin/api

**Comment by Craftsman96** [comment]
Nwm Sry xD is there a github side to read all api Methods etc. I dont see That there is a complete doc

**Comment by ChimpGamer** [comment]
I would suggest opening the api jar and look through all the classes to see the available options. If you have any questions you can ask them in the discord or here on github.
