### ISSUE TITLE
Party Warp

### ISSUE THREAD

**Issue by mishal321** [ChimpGamer/NetworkManager#78]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When you're in a party, either have it so that the people in your party will teleport to the server automatically, without doing /party jump. Or do /party warp, and all the people inside your party will warp automatically to your server.

**Describe alternatives you've considered**
Features like this, : https://www.spigotmc.org/resources/party-and-friends-for-bungeecord.9531/
**Additional context**

**Comment by ChimpGamer** [comment]
Added this in 2.13.0
