### ISSUE TITLE
Simplechat DiscordSRV incompat

### ISSUE THREAD

**Issue by mishal321** [ChimpGamer/NetworkManager#79]
**Is your feature request related to a problem? Please describe.**
Yes, SimpleChat will not work with DiscordSRv
**Describe the solution you'd like**
Make SimpleChat work with discordSRV

**Describe alternatives you've considered**
None
**Additional context**

**Comment by ChimpGamer** [comment]
Saying it doesn't work doesn't describe nor help me understand the problem. How can I solve the issue you're facing without description of the problem?

**Comment by mishal321** [comment]
Hi, sorry about that. When Simple chat is installed, it seems it does not go through the console, therefore DiscordSRV seems that it wont pick it up. 

![image](https://user-images.githubusercontent.com/72044822/117081721-15146800-ad06-11eb-8698-be5e30bf9451.png)

**Comment by ChimpGamer** [comment]
In the DiscordSRV there is a setting called "RespectChatPlugins". Try to disable that.

**Comment by mishal321** [comment]
There doesnt seem to be "RespectChatPlugins" on my config, here it is.
[1.txt](https://github.com/ChimpGamer/NetworkManager/files/6443773/1.txt)

**Comment by ChimpGamer** [comment]
Your Config is too old so it doesn't contain the setting.

**Comment by mishal321** [comment]
I've updated my discordsrv, and deleted the folder. And started the server again, and there still is no "RespectChatPlugins"

**Comment by ChimpGamer** [comment]
https://github.com/DiscordSRV/DiscordSRV/blob/41b8f04815b028463cbccec42664943b94c199a6/src/main/java/github/scarsz/discordsrv/DiscordSRV.java#L1555
Seems that the setting is still there. Add it manually to the config with false as value. I'll add a better solution for Paper users soon.

**Comment by mishal321** [comment]
Yep! Adding RespectChatPlugins: False does the job!

**Comment by Wild1145** [comment]
Just to note, it's not suggested to do this.

```
[12:25:11 WARN]: [DiscordSRV]

RespectChatPlugins is disabled, this option is for TESTING PURPOSES ONLY
and should NEVER be disabled on production servers.
Disabling the option will cause cancelled messages to be forwarded to Discord
including but not limited to private messages or staff chat messages without /commands
```

**Comment by ChimpGamer** [comment]
I know but it is the only way.

**Comment by Wild1145** [comment]
So to bump this, is there a better alternative than DiscordSRV as disabling the respect chat plugins works, but also breaks things like /mute so players can join, get muted in game and flood the Discord channel with all sorts of abuse. Just wondering if there is a better solution here?

**Comment by ChimpGamer** [comment]
If you use Paper 1.16.5 or newer this should be fixed. If you use Spigot then I suggest you switch to Paper or disable the RespectChatPlugins setting.
