### ISSUE TITLE
Tab header don't work.

### ISSUE THREAD

**Issue by DanielMarkink** [ChimpGamer/NetworkManager#8]
### What steps do you need to take to reproduce the problem?  
1.  Enable tab header.
2.  Wait minimum 3 min if it was off
3.  Press tab in the game.
(My result:
![2018-02-23_13 42 05](https://user-images.githubusercontent.com/30463195/36594724-b8c3569a-189f-11e8-920b-95c66bdcbb55.png)
)
etc.

### What were you expecting to happen? What happens instead?  
To change the tab.

### What version of the plugin are you using? (Type /networkmanager (In-Game)) 
![3](https://user-images.githubusercontent.com/30463195/36594739-c704edf4-189f-11e8-85d4-84bd41ca9b0f.PNG) 

### What BungeeCord/Spigot version are you using? (Type /bungee for BungeeCord and /version for Spigot)  
![2](https://user-images.githubusercontent.com/30463195/36594757-d5e6b442-189f-11e8-9400-865019f94395.PNG)
![4](https://user-images.githubusercontent.com/30463195/36594881-48e2634c-18a0-11e8-96ff-0c84abcf345d.PNG)

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com), [pastebin.com](http://pastebin.com) or insert a screenshot.
Nope.

**Comment by DanielMarkink** [comment]
And also on the latest version :(
![1](https://user-images.githubusercontent.com/30463195/36610524-e1fc3cd0-18d0-11e8-835e-9a30ba7e6677.PNG)

**Comment by ChimpGamer** [comment]
Like I said in the Discord this is because you are using BungeeCord Build 1300 or up. Use Build 1299 and it will work fine.
