### ISSUE TITLE
Anti-VPN / Anti-Bot

### ISSUE THREAD

**Issue by lucian929** [ChimpGamer/NetworkManager#80]
**Is your feature request related to a problem? Please describe.**
Kind of. When I first released my server, we were hit with a bot attack. Because I was silly and didn't have an anti-bot, we had to restart the server to get rid of all the bots and deal with the problem.

**Describe the solution you'd like**
A networkmanager built-in Anti-VPN and Anti-Bot system.

**Describe alternatives you've considered**
[This plugin](https://www.spigotmc.org/resources/⭐-epicguard-protect-your-server-from-bots-more-⭐.72369/), which uses proxycheck.io to check for proxies & vpns.

**Comment by ChimpGamer** [comment]
I would recommend the alternative you described as well. I use it myself too and it works fine. It's not really something I would consider implementing into NetworkManager since there will be much better alternatives out there that keep on evolving faster then I'll be able to.

**Comment by lucian929** [comment]
Good to know - thank you!
