### ISSUE TITLE
Variable Announcements

### ISSUE THREAD

**Issue by lucian929** [ChimpGamer/NetworkManager#82]
**Is your feature request related to a problem? Please describe.**
It bothers me that for some small features I need to get a separate plugin rather than use what's built into NM.

**Describe the solution you'd like**
I want to be able to choose the time delay for announcements, and maybe let it send a random one every X minutes. Would be really useful for things like tips/tricks in chat.

**Describe alternatives you've considered**
https://www.spigotmc.org/resources/messageannouncer.5408/ on all of my spigot servers

**Additional context**
n/a

**Comment by ChimpGamer** [comment]
You can configure the interval of the announcements in the Settings.
`setting_chat_announcements_interval`
`setting_actionbar_announcements_interval`
`setting_title_announcements_interval`

**Comment by lucian929** [comment]
Yes, but you can't change it for individual announcements which is what I'm thinking of, or maybe even a system where it sends a random announcement from the list.

**Comment by ChimpGamer** [comment]
Then you'll have to create a new task for every announcement and set an interval for every announcement which will probably cross each other eventually. That's not really efficient which is why no announcement plugin does that.

**Comment by lucian929** [comment]
Closing because it would be inefficient, found another solution
