### ISSUE TITLE
NMSync Extension

### ISSUE THREAD

**Issue by lucian929** [ChimpGamer/NetworkManager#83]
**Is your feature request related to a problem? Please describe.**
I wish I could easily sync my player data across my lobbies

**Describe the solution you'd like**
I would like a feature that would allow you to sync a folder or config folder across multiple servers (within a server group would be great)

**Describe alternatives you've considered**
https://www.spigotmc.org/resources/mysql-player-data-bridge.8117/

**Additional context**
Example:
Let's say I want to change my essentials messages config file across my servers quickly.
I would change the config file on the primary server (which in this case, would be a lobby)
NMSync would then take this file and copy it over to the other servers within the group (or, it could ask you which servers to sync to)

**Comment by ChimpGamer** [comment]
Don't think it would be efficient to do that using a plugin. Also, plugins can't copy files to folders outside the root of the server instance without permissions.

**Comment by lucian929** [comment]
Something like MySQL player bridge (the spigot link I sent) would be possible though to do, right? I feel like it might make sense

**Comment by ChimpGamer** [comment]
That does only sync player data not configurations like you described in the solution.

**Comment by lucian929** [comment]
True. I'll close this, but I do like the idea and I think even just the player data sync would be nice.
