### ISSUE TITLE
Simplechat: @Ping players

### ISSUE THREAD

**Issue by lucian929** [ChimpGamer/NetworkManager#87]
**Is your feature request related to a problem? Please describe.**
Occasionally, a player may be AFK or not looking at their game and you want to get their attention.

**Describe the solution you'd like**
A feature to ping players. Uses permission `simplechat.ping`, and looks something like this.
![image](https://user-images.githubusercontent.com/60053521/130523293-5429fa0b-31c8-4d83-bcd3-ee95e4eba434.png)
Additionally has an option to play a sound for the pinged player, you can choose the sound in settings.

**Describe alternatives you've considered**
Finding another plugin for it

**Additional context**
That's all!

**Comment by ChimpGamer** [comment]
Added this feature. See #beta-builds in the discord server. This feature is currently in beta.

**Comment by lucian929** [comment]
- Option to choose the prefix (or have no prefix, so you can just say `Lucian929`
- Option for a color that other people see (so they can tell you mentioned a player)

**Comment by ChimpGamer** [comment]
You can change the color of mentions already or isn't that what you mean?

**Comment by lucian929** [comment]
> You can change the color of mentions already or isn't that what you mean?

You can only change the main color, here's an example of what I want to do:
Mentioned player sees blue
Everyone else in chat would see the blue as pink.

**Comment by ChimpGamer** [comment]
What is the point of that exactly?

**Comment by lucian929** [comment]
I don't think it has a full point, could be nice thoug.

**Comment by ChimpGamer** [comment]
I think it would be better to determine the color by using a placeholder (which is allowed). I'm closing this issue for now.
