### ISSUE TITLE
New features for DiscordBot Extension

### ISSUE THREAD

**Issue by lucian929** [ChimpGamer/NetworkManager#88]
**Is your feature request related to a problem? Please describe.**
I want to be able to remind players to join our discord and give them rewards.

**Describe the solution you'd like**
Two things:

1 - Execute commands (proxy or server side, server side will be more important for me.) when the player links their account
2 - Send a message or execute a command when the player does not have their account linked

**Describe alternatives you've considered**
I don't think there are any at the moment sadly

**Additional context**
N/A

**Comment by ChimpGamer** [comment]
This has been implemented in the latest version of NetworkManager and the DiscordBot. Point 1 has been added to the DiscordBot. Point 2 has sort of been realised by adding conditions to Announcements. Using the conditions you can send announcements based on a placeholder value. With the %discord_is_registered% placeholder you can send the message the players if the value is false.
