### ISSUE TITLE
Ticket system not 100% Fixed :(

### ISSUE THREAD

**Issue by DanielMarkink** [ChimpGamer/NetworkManager#9]
### What steps do you need to take to reproduce the problem?  
1. Open an ticket.
2. Anser via the webpanel
3. Look into the ticket from the ticket system (/tickets/ticket.php)
4. Logo of the staff will be not displayed.

### What were you expecting to happen? What happens instead?  
display the staff mc picture.

### What version of the plugin are you using? (Type /networkmanager (In-Game))  
Latest

### What BungeeCord/Spigot version are you using? (Type /bungee for BungeeCord and /version for Spigot)  
Latest

### Any additional information that might be useable/important?
![1](https://user-images.githubusercontent.com/30463195/36643529-c5a4d2fe-1a4c-11e8-8a18-cbac40eb8d17.PNG)

**Comment by ChimpGamer** [comment]
In the code only UUID's are being used.

**Comment by DanielMarkink** [comment]
Nope. You call it in the table an UUID but it stores an PlayerName.

**Comment by DanielMarkink** [comment]
So or only insert an UUID on the table or stre it an an Username and get the UUID with the php files.

**Comment by ChimpGamer** [comment]
We only insert UUID's in the UUID row. With the Plugin and the ticket interface as well.

**Comment by ChimpGamer** [comment]
Will be fixed in the next Interface update for eveyone!
