### ISSUE TITLE
DiscordBot Features

### ISSUE THREAD

**Issue by lucian929** [ChimpGamer/NetworkManager#90]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
Add the discordbot_isregistered placeholder to the NetworkManager spigot jar so it can be used on actual servers instead of just the proxy. Additionally, add a feature to execute commands when a player links their account. Right now, I have to do it manually.

**Describe alternatives you've considered**
DiscordSRV (definitely don't want to to this)

**Additional context**
Conversation on Discord:
https://discord.com/channels/222070253172031500/341357067619139585/884780867426349077

**Comment by lucian929** [comment]
Feature 2 was implemented, feature one was not

**Comment by lucian929** [comment]
One more feature request - a way to change how NM nicknames verified players. I want to have a format that looks something like this for a users Discord username:

Raindropz#0766 [Lucian929]

**Comment by ChimpGamer** [comment]
> One more feature request - a way to change how NM nicknames verified players. I want to have a format that looks something like this for a users Discord username:
> 
> `Raindropz#1712 [Lucian929]` So, in the config it could be something like:
> 
> ```
>     sync:
>       username: true
>       format: "%discordname% [%playername%]" # this is the newline
> ```

Added in DiscordBot version 1.4.0
