### ISSUE TITLE
Simplechat ClickCommand force execute

### ISSUE THREAD

**Issue by werken23** [ChimpGamer/NetworkManager#93]
**Is your feature request related to a problem? Please describe.**
Currently simplechat's ClickCommand does not execute the command but only pastes it in the chat.

**Describe the solution you'd like**
A config option for the ClickCommand to force execute commands on click. Example: "prefixForceExecute: true" or "prefixClickCommand: '/command' -f''.

**Comment by ChimpGamer** [comment]
This will be possible in SimpleChat 2.0.0 (which is already done) which will be available with the NetworkManager 2.11.0 release.

**Comment by ChimpGamer** [comment]
NetworkManager 2.11.0 has been released and so has SimpleChat 2.0.0 which now supports this feature using the minimessage format.
