### ISSUE TITLE
Hook into PartyAndFriends

### ISSUE THREAD

**Issue by KidIsMyLover** [ChimpGamer/NetworkManager#95]
Hook into it so we can look its party and friend msg's chat log
Plugin link:https://www.spigotmc.org/resources/party-and-friends-for-bungeecord-supports-1-7-x-to-1-18-x.9531/

**Comment by ChimpGamer** [comment]
I will try to add this. If I'm able to add it then I will try to add this in the 1.12.0 release.

**Comment by ChimpGamer** [comment]
This was added in the 2.12.0 release.
