### ISSUE TITLE
Discord bot update for Litebans addon

### ISSUE THREAD

**Issue by REGENTUM** [ChimpGamer/NetworkManager#99]
The bot performs a variety of functions to relay information from the server. I would like to be able to receive information about punishments not only from the built-in punishment manager, but also from the LiteBans add-on. Thanks)

**Comment by ChimpGamer** [comment]
I think I'll be able to add this after I managed to update to JDA v5.

**Comment by ChimpGamer** [comment]
Added this in the latest beta build of DiscordBot 1.7.0 but I have not been able to test it. You can find the build in the discord server.
